# Generated by Django 4.0.5 on 2022-07-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
