# Generated by Django 4.0.5 on 2022-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_remove_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='msg',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
